language: go

go:
  - "1.10"

install: true

sudo: true

#dont email me i dont like spam
notifications:
  email: false

before_script:
  - go get github.com/mdaffin/go-telegraf
  - go get golang.org/x/crypto/ssh
  - go get gopkg.in/mgo.v2
  - go get github.com/BurntSushi/toml
  - go get github.com/fsnotify/fsnotify
  - go get github.com/garyhouston/tiff66
  - go get github.com/garyhouston/exif44
  - go get -u golang.org/x/image/bmp
  - go get -u golang.org/x/image/tiff
  - go get -u golang.org/x/image/tiff/lzw
  - go get github.com/golang/lint/golint
  - go get -u github.com/fogleman/gg
  - go get -u golang.org/x/image/font/gofont/goregular


script:
  - golint -set_exit_status
  - "./build.sh"

before_deploy:
  - git config --local user.name "zarlo"
  - git config --local user.email "zarlo5899@gmail.com"

deploy:
  provider: releases
  api_key: $TOKEN
  file_glob: true
  file:
    - "bin/*"
  name: Release $TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true
