- include_tasks: tasks/aur.yml pkg_name="lsyncd"

- name: create lsyncd config directory
  file:
    path: /etc/lsyncd/
    state: directory

- name: lsyncd configuration file
  copy:
    src: lsyncd.conf.lua
    dest: /etc/lsyncd/lsyncd.conf.lua

- name: lsyncd service
  copy:
    src: lsyncd.service
    dest: /usr/lib/systemd/system/lsyncd.service

- name: enable lsyncd
  systemd:
    name: lsyncd.service
    daemon_reload: yes
    state: restarted
    enabled: yes
    masked: no
